AWSTemplateFormatVersion: "2010-09-09"
Description: Cfn sample Security Stack

Parameters:
  SecurityGroupName:
    Type: String
    Description: Name of the SecurityGroup
  S3BucketURL:
    Type: String
    Description: URL of the S3 bucket containing the templates
  S3Bucket:
    Type: String
    Description: URL of the S3 bucket containing the templates
  PolicyName:
    Type: String
    Description: Name of the IAM Policy
  RoleName:
    Type: String
    Description: Name of the IAM Role
  Ec2KeyPairName:
    Type: String
    Description: The name of the key pair to be created.

Resources:
  SecurityGroupStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${S3BucketURL}/security-group.yaml"
      Parameters:
        VpcId: !ImportValue NetworkStack-VpcId
        SecurityGroupName: !Ref SecurityGroupName

  IAMPolicyStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${S3BucketURL}/iam-policy.yaml"
      Parameters:
        PolicyName: !Ref PolicyName
        S3Bucket: !Ref S3Bucket

  IAMRoleStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${S3BucketURL}/iam-role.yaml"
      Parameters:
        RoleName: !Ref RoleName
        PolicyArn: !GetAtt IAMPolicyStack.Outputs.PolicyArn

  Ec2KeyPairStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${S3BucketURL}/ec2keypair.yaml"
      Parameters:
        KeyPairName: !Ref Ec2KeyPairName

Outputs:
  SecurityGroupId:
    Description: The ID of the security group
    Value: !GetAtt SecurityGroupStack.Outputs.SecurityGroupId
    Export:
      Name: SecurityStack-SecurityGroupId
  IAMPolicyArn:
    Description: The ARN of the managed policy
    Value: !GetAtt IAMPolicyStack.Outputs.PolicyArn
    Export:
      Name: SecurityStack-IAMPolicyArn
  IAMRoleArn:
    Description: The ARN of the IAM role
    Value: !GetAtt IAMRoleStack.Outputs.RoleArn
    Export:
      Name: SecurityStack-IAMRoleArn
  IAMRoleName:
    Description: The Name of the IAM role
    Value: !GetAtt IAMRoleStack.Outputs.RoleName
    Export:
      Name: SecurityStack-RoleName
  InstanceProfileName:
    Description: The Name of the IAM role
    Value: !GetAtt IAMRoleStack.Outputs.InstanceProfileName
    Export:
      Name: SecurityStack-InstanceProfileName
  Ec2KeyPairName:
    Description: The Ec2 Key Pair Name
    Value: !GetAtt Ec2KeyPairStack.Outputs.Ec2KeyPairName
    Export:
      Name: SecurityStack-Ec2KeyPairName
