AWSTemplateFormatVersion: "2010-09-09"
Description: IAM Role for EC2 Session Manager Access

Parameters:
  RoleName:
    Type: String
    Description: Name of the IAM Role
  PolicyArn:
    Type: String
    Description: The ARN of the managed policy to attach

Resources:
  EC2SessionManagerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref RoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - !Ref PolicyArn
  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2SessionManagerRole

Outputs:
  RoleArn:
    Description: The ARN of the IAM role
    Value: !GetAtt EC2SessionManagerRole.Arn
    Export:
      Name: IAMRole-RoleArn
  RoleName:
    Description: The name of the IAM role
    Value: !Ref EC2SessionManagerRole
    Export:
      Name: IAMRole-RoleName
  InstanceProfileName:
    Description: The name of the IAM Instance Profile
    Value: !Ref EC2InstanceProfile
    Export:
      Name: IAMRole-InstanceProfileName
