AWSTemplateFormatVersion: "2010-09-09"
Description: IAM Policy for EC2 Session Manager Access

Parameters:
  PolicyName:
    Type: String
    Description: Name of the IAM Policy
  S3Bucket:
    Type: String
    Description: URL of the S3 bucket containing the policy document

Resources:
  EC2SessionManagerPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Ref PolicyName
      PolicyDocument:
        Fn::Transform:
          Name: "AWS::Include"
          Parameters:
            Location: !Sub "s3://${S3Bucket}/security/policy.json"

Outputs:
  PolicyArn:
    Description: The ARN of the managed policy
    Value: !Ref EC2SessionManagerPolicy
    Export:
      Name: IAMPolicy-PolicyArn
